# Generated by Django 5.0.2 on 2024-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_list', models.CharField(max_length=30)),
                ('status_list', models.IntegerField()),
                ('chat', models.CharField(max_length=20)),
                ('group_list', models.IntegerField()),
            ],
        ),
    ]
